ANIMAL_LIST = [
    "Canidae",
    "Felidae",
    "Cat",
    "Cattle",
    "Dog",
    "Donkey",
    "Goat",
    "Guinea pig",
    "Horse",
    "Pig",
    "Rabbit",
    "Rat",
    "Sheep",
    "Water buffalo",
    "Chicken",
    "Duck",
    "Goose",
    "Pigeon",
    "Turkey",
    "Aardvark",
    "African buffalo",
    "African elephant",
    "African leopard",
    "Albatross",
    "Alligator",
    "Alpaca",
    "American buffalo",
    "American robin",
    "Amphibian",
    "Anaconda",
    "Angelfish",
    "Anglerfish",
    "Ant",
    "Anteater",
    "Antelope",
    "Antlion",
    "Ape",
    "Aphid",
    "Arabian leopard",
    "Arctic Fox",
    "Arctic Wolf",
    "Armadillo",
    "Arrow crab",
    "Donkey",
    "Baboon",
    "Badger",
    "Bald eagle",
    "Bandicoot",
    "Barnacle",
    "Barracuda",
    "Basilisk",
    "Bass",
    "Bat",
    "Beaked whale",
    "Bear",
    "Beaver",
    "Alligator",
    "Alpaca",
    "American buffalo",
    "American robin",
    "Amphibian",
    "Bedbug",
    "Bee",
    "Beetle",
    "Bird",
    "Bison",
    "Blackbird",
    "Black panther",
    "Black widow spider",
    "Blue bird",
    "Blue jay",
    "Blue whale",
    "BoaBoar",
    "Bobcat",
    "Bobolink",
    "Bonobo",
    "Booby",
    "Box jellyfish",
    "Bovid",
    "Bug",
    "Butterfly",
    "Buzzard",
    "Camel",
    "Canid",
    "Capybara",
    "Cardinal",
    "Caribou",
    "Carp",
    "Catshark",
    "Caterpillar",
    "Catfish",
    "Cattle",
    "Centipede",
    "Cephalopod",
    "Chameleon",
    "Cheetah",
    "Chickadee",
    "Chimpanzee",
    "Chinchilla",
    "Chipmunk",
    "Clam",
    "Clownfish",
]
